- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    certmgr_base_url: https://cert-manager.com/api
    certmgr_endpoint: /organization/v1
  tasks:
    - name: Get vaulted credentials
      include_vars: vars/incommon-vault.yml
      tags: always
    - name: Set auth variables
      set_fact:
        certmgr_user: "{{ vault_certmgr_user }}"
        certmgr_pass: "{{ vault_certmgr_pass }}"
        certmgr_uri: "{{ vault_certmgr_uri }}"
    - name: Set up Headers
      set_fact:
        certmgr_headers:
          login: "{{ certmgr_user }}"
          password: "{{ certmgr_pass }}"
          customerUri: "{{ certmgr_uri }}"
    - name: Run call against api endpoint
      uri:
        url: "{{ certmgr_base_url }}/{{certmgr_endpoint }}"
        method: GET
        headers: "{{ certmgr_headers }}"
        body_format: json
        return_content: true
      register: api_call
    - debug:
        var: api_call
